# Site settings
email: 
baseurl: "https://lonesomeguy.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: The blog of lonesome guy
description: :)
url: "https://lonesomeguy.github.io"
twitter_username: 
default_img: 

# Profile settings
name: lonesomeguy
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
