# Site settings
email: 
baseurl: "https://lonesomeguy.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Anh Tu's Blog
description: a personal blog
url: "https://lonesomeguy.github.io"
twitter_username: anhtu2505
default_img: https://1.bp.blogspot.com/-8d6IJVBGiIw/VGIiRTXFxXI/AAAAAAAAM_w/Ftlj6hpCto8/s0/featured-image.jpg

# Profile settings
name: Anh Tu
profile_img: http://i.imgur.com/zvKlNvR.jpg
profile: a student who interest in web-designing and blogging
social:
  github: https://github.com/lonesomeguy
  facebook: https://www.facebook.com/anhtu255
  google-plus: https://plus.google.com/107458005734150435400
  soundcloud: https://soundcloud.com/kudo2505
  instagram: https://instagram.com/anhtu2505

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
